### ISSUE TITLE
First test build

### ISSUE THREAD

**Issue by guoyunhe** [guoyunhe/medes#3]
Need to finish user profile view and editing:
1. User menu(on top of site): user icon and user name.
2. Register popup (almost done)
3. Profile editing popup (half)
4. Profile view popup (half)
5. New login popup

**Comment by EloiseSmith-Foster** [comment]
Great job the site is looking good :) a few points from me:
1. In the section BASIC INFORMATION I think it would be clearer if it said "can't be changed" instead of "Cannot change"
2. It says "Master of Europe Design" in top left corner of website, should be "Master of European Design"
3. In MEDES PATH section the "teacher" and "tutor" should just have one box to write one school into.
4. EXPERIENCE section title should be changed to WORK EXPERIENCE so it is a bit clearer to the user what type of experience we mean.
5. In DESCRIPTION section - it could say "Description of your design philosophy" and "Tagline - write about yourself" so the user knows.
6. In the final version of the profile, when I finish editing the hashtags are missing from the skills.
7. In the timeline that appears it could have a title above it saying "Work Experience" so that it is clear.
8. When I go on someone elses profile it still says "edit" in the top right hand corner. It makes it seem as if I can edit their profile.
